### PR TITLE
Add ubuntu, buster-arm, fedora, macos and windows  packaging

### LINKED ISSUE #1: Implement Windows installer
The Windows installer should be an MSI package that:

- provides the MSVC runtime and Gstreamer plugins as merge modules (static CRT link can then be removed).
- installs a Start Menu icon
- Runs as a Windows service
- Pulls the configuration from `C:\ProgramData\Neolink`

### LINKED ISSUE #61: Creating Packages
It would ease installation considerably if we had packages such as `.deb` or a `Brewfile` maybe even a choco.

I can make the macos one (`Brewfile`) although we'd need a permalink to a version which won't work with the current CI style deployment.

I might be able to make a `deb` one too, but I generally don't touch windows so I can't do the choco.

### PR DESCRIPTION
**Pull request by QuantumEntangledAndy**
This adds packages for various distros of linux and macos.

The debian packages are made with cargo-deb and the fedora with cargo-rpm

The macos package waa originally a homebrew tab but I have since swapped it to a PKG (installer). 

---
## Useage

- Debian, (ubuntu amd64/buster armhf)
  1. Download deb
  2. Install neolink
    ```bash
    apt install ./name_of_downloaded_deb.deb
    ```
- Fedora (amd64)
  1. Download rpm
  2. Install neolink
  ```bash
   yum install ./name_of_downloaded_rpm.rpm
   ```
- Macos
   1. Download PKG
   2. Double click to install

- Windows
   1. Download msi
   2. Double click to install

---
Closes #61 
Closes #1 🎉  (well not the service part but that should be on the todo list)

### CODE REVIEW

**Comment by thirtythreeforty** [comment]
Thanks for this. Sorry I've been quiet for a while, I just bought a house and I'm in the process of moving in. I will try to review Real Soon Now :)

**Comment by QuantumEntangledAndy** [comment]
Congratulations :). Take your time, moving in takes much longer than we think :).

Also I'm planning to add a window msi using cargo Wix too then we will have all the OSes.

**Comment by QuantumEntangledAndy** [comment]
So I am trying to setup a windows test environment in Virtual Box. I am having trouble building neolink, as I cannot seem to link glib2 any idea how to resolve this? I've gotten the libraries installed but I am not sure how to set the library search path on windows... sigh

**Comment by QuantumEntangledAndy** [comment]
Nevermind I got glib and gobject to work but I am struggling to link gstreamer now... The same method I used for glib dosen't seem to work for gstreamer

fyi to those interested used this in the `.cargo/config`, with the gtk runtime from chocolatley

```toml
[target.x86_64-pc-windows-msvc.glib]
rustc-link-search = ["C:\\Program Files (x86)\\GTK2-Runtime\\bin"]

[target.x86_64-pc-windows-msvc.gobject]
rustc-link-search = ["C:\\Program Files (x86)\\GTK2-Runtime\\bin"]
```

**Comment by QuantumEntangledAndy** [comment]
Ok I had to add `%GSTREAMER_1_0_ROOT_X86_64%\bin` to the PATH and then it found it, not sure why rustc-link-search did not find it though

**Comment by QuantumEntangledAndy** [comment]
I think I have a working msi for neolink, only I couldn't get the dependency check on gstreamer to work correctly. Will look into it when I can

**Comment by QuantumEntangledAndy** [comment]
Given our discussion in #59 I am swapping the mac build to use the pkg from gstreamer (since the pkg installer explicitly searches for it in /Library/Framework/Gstreamer.framework)

**Comment by QuantumEntangledAndy** [comment]
So I am relatively happy with how this is working.

There is a further imporement that we could do:

- We can package gstreamer into the win and mac installers.

This would mean that we would need to ship it bundled together with gstreamer 

  - wixtoolset dosen't support remote download for msi (only exe installers)
  -  mac pkg times out during download because of its size.

This will mean that it will bump up the size of our packages by about 100MB

**Comment by thirtythreeforty** [comment]
> wixtoolset dosen't support remote download for msi (only exe installers)

The sanctioned approach for WiX is to use the merge module that Gstreamer ships with their dev package. The merge module will literally merge with the MSI and become a single installable. I've done it before for the MSVC runtime; it's quite clean.

I don't have a strong opinion about the Mac pkg yet.

**Comment by QuantumEntangledAndy** [comment]
- Win: I have added the merge modules into the msi (havent tested yet as need to get my win VM back up)

- Mac: I have put gstreamer into the post install script as suggested in the [gstraemer docs](https://gstreamer.freedesktop.org/documentation/deploying/mac-osx.html?gi-language=c)

**Comment by QuantumEntangledAndy** [comment]
In terms of addind services would you be ok with using [nssm](https://github.com/kirillkovalenko/nssm)

**Comment by QuantumEntangledAndy** [comment]
With no progress on my PRs in years I am closing them in favour of working on my own fork

**Pull request closed without merging**
