### PR TITLE
Update documentation for status code and additional encryption offset data

### PR DESCRIPTION
**Pull request by twistedddx**

### CODE REVIEW

**Comment by thirtythreeforty** [comment]
The documentation update is good, I will have to update the Baichuan parser based on the status fields you figured out. Thanks.

**Review by thirtythreeforty — APPROVED** [review]

**Comment by twistedddx** [comment]
Dissector does already include status code from a previous commit. Although at the time I had called it "error_code".

**Comment by thirtythreeforty** [comment]
True. I meant in Neolink itself.

**Comment by QuantumEntangledAndy** [comment]
I have started adding status codes and message handle to neolink already as part as  #83 but never have had time to finish it :(. Buzy work things these days

**Pull request merged**
