### PR TITLE
Motion Detection

### PR DESCRIPTION
**Pull request by QuantumEntangledAndy**
This PR adds motion detection to `neolink_core`

- It also contains some small fixes to documentation and comments

- Additionally, while writing the motion detection code I made the callback be able to gracefully shutdown the motion detection loop returning `Ok(false)`.
  - I thought this was a nice feature so I added it to the stream callback too (although it is mostly unused in our own code it may be of use as part of the library)
  - Let me know if you want me to drop this

### CODE REVIEW

**Comment by 0dragosh** [comment]
This is quite neat; am I correct in assuming this will help us get a person/vehicle detected event off of the camera and integrate it with something HASS?

**Comment by QuantumEntangledAndy** [comment]
@0dragosh This PR by itself just opens up the Motion detection protocol for other apps to use. But if coupled with the mqtt PR it will give a way to pass that MD message on to other apps.

**Comment by 0dragosh** [comment]
> @0dragosh This PR by itself just opens up the Motion detection protocol for other apps to use. But if coupled with the mqtt PR it will give a way to pass that MD message on to other apps.

Gotcha! Good work!

**Comment by marcosandremartins** [comment]
Is this PR dead?

**Comment by QuantumEntangledAndy** [comment]
Most of my PRs seem to be :(. There's no comment from the repo owner on why they cannot be merged and I cannot merge it without approval.

**Comment by marcosandremartins** [comment]
Hi @thirtythreeforty 
Can we get your help on this? A lot of interesting things are on queue to be merged.

**Comment by anthonws** [comment]
+1 I can't say how cool it would be to have this checked in into main.
@QuantumEntangledAndy this can nevertheless be used with your fork, correct? I am using the docker image from your fork.
I will try it out and will report.
Thanks!

**Comment by QuantumEntangledAndy** [comment]
Yes it can be used on my fork. I'm in the process of putting all my different unmerged features into my fork's main branch so we can enjoy all the extra features at once.

**Comment by thirtythreeforty** [comment]
Hey all. Sorry for being absent. (I had a baby late August and then... holidays.  Excuses, excuses.)

This looks great (and yes I did review it). Thanks @QuantumEntangledAndy. No issue merging this here! I will review the MQTT stuff next.

**Comment by QuantumEntangledAndy** [comment]
@thirtythreeforty congratulations and also welcome to the no-sleep club.

I've got a lot of changes on my forks master branch that are not included such as warning/errors when gts plugins are missing.

To get all the features from my PRs to merge it requires some changes (the joys of having multiple branches waiting so long between merges is that there's no good coming reference point). I have done this on my forks main branch. But it was a lot of work and not sure how to lay all the changes required out to you in small sequential PRs. Any chance you'll look at all my changes in one combined PR?

**Pull request merged**
